# **Exp1. SETTING UP THE ENVIRONMENT AND PREPROCESSING DATA FOR ML APPLICATIONS**

##**1. Aim**

To perform data preprocessing on a Student Performance dataset using Python and Pandas before applying a Machine Learning algorithm.

## **2. What is Data Preprocessing?**

Data preprocessing is the process of cleaning, transforming, and preparing raw data before applying a Machine Learning algorithm.

Real-world datasets may contain:

- Missing values
- Duplicate records
- Invalid values
- Categorical data
- Unnecessary columns
- Different numerical scales

Therefore, data preprocessing is an important step in Machine Learning.

## **3. Dataset Description**

The Student Performance dataset contains information about students, including their attendance, study hours, previous grades, parental support, extracurricular activities, and final grades.

The dataset contains 1000 records and 12 columns.

### Dataset Columns

| Column | Description |
|---|---|
| `StudentID` | Unique identification number of the student |
| `Name` | Name of the student |
| `Gender` | Gender of the student |
| `AttendanceRate` | Attendance rate of the student |
| `StudyHoursPerWeek` | Number of study hours per week |
| `PreviousGrade` | Previous academic grade |
| `ExtracurricularActivities` | Number/level of extracurricular activities |
| `ParentalSupport` | Level of parental support |
| `FinalGrade` | Final academic grade |
| `Study Hours` | Study hours |
| `Attendance (%)` | Attendance percentage |
| `Online Classes Taken` | Whether the student attended online classes |

##Step 1 – Import Required Libraries

In [38]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, StandardScaler

* **pandas** is used to load, manipulate, and analyze the dataset.
* **numpy** is used for numerical operations.
* **train_test_split** is used to divide the dataset into training and testing data.
* **LabelEncoder** is used to convert categorical values into numerical values.
* **StandardScaler** is used to perform feature scaling.

## Step 2 – Load the Dataset

In [39]:
dataset = "https://raw.githubusercontent.com/ParamesManthiramoorthi26/MachineLearningLab_Exp/refs/heads/main/Exp%20-%20(1)/dataset/student_performance_dataset.csv"
student = pd.read_csv(dataset)
student.head()

,StudentID,Name,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade,Study Hours,Attendance (%),Online Classes Taken
0,1.0,John,Male,85.0,15.0,78.0,1.0,High,80.0,4.8,59.0,False
1,2.0,Sarah,Female,90.0,20.0,85.0,2.0,Medium,87.0,2.2,70.0,True
2,3.0,Alex,Male,78.0,10.0,65.0,0.0,Low,68.0,4.6,92.0,False
3,4.0,Michael,Male,92.0,25.0,90.0,3.0,High,92.0,2.9,96.0,False
4,5.0,Emma,Female,NaN,18.0,82.0,2.0,Medium,85.0,4.1,97.0,True

* The **read_csv()** function is used to load the CSV file into a Pandas DataFrame.

* The **head()** function displays the first five rows of the dataset.

## Step 3 – Understand the Dataset

In [40]:
print("Dataset Shape:",student.shape)
print("No of Rows",student.shape[0])
print("No of Columnss",student.shape[1])

Dataset Shape: (1000, 12)
No of Rows 1000
No of Columnss 12

In [41]:
print("\nColumn Names:")
print(student.columns)

Column Names:
Index(['StudentID', 'Name', 'Gender', 'AttendanceRate', 'StudyHoursPerWeek',
       'PreviousGrade', 'ExtracurricularActivities', 'ParentalSupport',
       'FinalGrade', 'Study Hours', 'Attendance (%)', 'Online Classes Taken'],
      dtype='object')

In [42]:
print("\nDataset Information:")
print(student.info())

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   StudentID                  960 non-null    float64
 1   Name                       966 non-null    object
 2   Gender                     952 non-null    object
 3   AttendanceRate             960 non-null    float64
 4   StudyHoursPerWeek          950 non-null    float64
 5   PreviousGrade              967 non-null    float64
 6   ExtracurricularActivities  957 non-null    float64
 7   ParentalSupport            978 non-null    object
 8   FinalGrade                 960 non-null    float64
 9   Study Hours                976 non-null    float64
 10  Attendance (%)             959 non-null    float64
 11  Online Classes Taken       975 non-null    object
dtypes: float64(8), object(4)
memory usage: 93.9+ KB
None

In [43]:
print("\nStatistical Summary:")
student.describe().transpose()

Statistical Summary:

,count,mean,std,min,25%,50%,75%,max
StudentID,960.0,5416.019792,2653.748319,1.0,3113.5,5396.5,7754.75,9998.0
AttendanceRate,960.0,85.510417,7.332125,70.0,82.0,88.0,91.00,95.0
StudyHoursPerWeek,950.0,17.630526,6.272132,8.0,12.0,18.0,22.00,30.0
PreviousGrade,967.0,77.598759,10.006640,60.0,70.0,78.0,86.00,90.0
ExtracurricularActivities,957.0,1.520376,1.046439,0.0,1.0,1.0,2.00,3.0
FinalGrade,960.0,80.030208,9.493652,62.0,72.0,80.0,88.00,92.0
Study Hours,976.0,2.406967,1.620267,-5.0,1.2,2.5,3.70,5.0
Attendance (%),959.0,77.248175,19.298148,50.0,63.0,76.0,89.00,200.0

**Issues Found** :
* Some columns have fewer than 1000 values, indicating missing data.
* Two invalid values are identified:
  * Study Hours     : -5
  * Attendance (%)  : 200
* **StudentID** is only an identifier and does not provide useful information for prediction.
* Some column names in our dataset contain spaces and special characters.
Examples:

```text
Study Hours
Attendance (%)
Online Classes Taken
```

* For easier coding, we can remove spaces and special characters from column names. Column names should be standardized before starting the main preprocessing steps. This makes the remaining Python code easier to read, write, and maintain.

## Step 4 – Standardize Column Names

In [44]:
student.columns = (
    student.columns
    .str.strip()
    .str.replace(' ', '_')
    .str.replace(r'[%()]', '', regex=True)
)

print(student.columns)

Index(['StudentID', 'Name', 'Gender', 'AttendanceRate', 'StudyHoursPerWeek',
       'PreviousGrade', 'ExtracurricularActivities', 'ParentalSupport',
       'FinalGrade', 'Study_Hours', 'Attendance_', 'Online_Classes_Taken'],
      dtype='object')

* strip() :  removes extra spaces at the beginning/end.
* replace(' ', '_')  :  replaces spaces with _.
* replace() :  removes special characters like %, ( and ).

## Step 5 – Handle Invalid Values

Identified two invalid values during the initial analysis:


  * **Study_Hours** = -5    : study hours cannot be negative.
  * **Attendance_** = 200   : attendance percentage cannot exceed 100%.

In [45]:
# Replace Invalid Values with NaN
student.loc[student['Study_Hours'] < 0, 'Study_Hours'] = np.nan

student.loc[student['Attendance_'] > 100, 'Attendance_'] = np.nan

## Step 6 – Check Missing Values

In [46]:
print(student.isnull().sum())

StudentID                    40
Name                         34
Gender                       48
AttendanceRate               40
StudyHoursPerWeek            50
PreviousGrade                33
ExtracurricularActivities    43
ParentalSupport              22
FinalGrade                   40
Study_Hours                  34
Attendance_                  51
Online_Classes_Taken         25
dtype: int64

* **isnull()** identifies missing values.
* **sum()** counts the missing values in each column.

## **Observation**
* **StudentID** and **Name** are identifier columns and do not provide useful information for ML prediction.
* Therefore, these columns are removed before handling missing values.
* Missing values in **numerical** feature columns are replaced with the **median**.
* Missing values in **categorical** feature columns are replaced with the **mode**.

## Step 7 – Remove Unnecessary Columns

In [47]:
student = student.drop(columns=['StudentID', 'Name'])

print(student.columns)

Index(['Gender', 'AttendanceRate', 'StudyHoursPerWeek', 'PreviousGrade',
       'ExtracurricularActivities', 'ParentalSupport', 'FinalGrade',
       'Study_Hours', 'Attendance_', 'Online_Classes_Taken'],
      dtype='object')

## Step 8 – Handle Missing Values

### Numerical columns – Median

In [48]:
num_cols = student.select_dtypes(include='number').columns
print("Before numerical columns")
print("*" * 30)
print(student[num_cols].isnull().sum())

for col in num_cols:
    student[col] = student[col].fillna(student[col].median())

print("\n After numerical columns")
print("*" * 30)
print(student[num_cols].isnull().sum())

Before numerical columns
******************************
AttendanceRate               40
StudyHoursPerWeek            50
PreviousGrade                33
ExtracurricularActivities    43
FinalGrade                   40
Study_Hours                  34
Attendance_                  51
dtype: int64

 After numerical columns
******************************
AttendanceRate               0
StudyHoursPerWeek            0
PreviousGrade                0
ExtracurricularActivities    0
FinalGrade                   0
Study_Hours                  0
Attendance_                  0
dtype: int64

### Categorical columns – Mode

In [49]:
cat_cols = student.select_dtypes(include='object').columns

print("Before numerical columns")
print("*" * 30)
print(student[cat_cols].isnull().sum())

for col in cat_cols:
    student[col] = student[col].fillna(student[col].mode()[0])

print("After numerical columns")
print("*" * 30)
print(student[cat_cols].isnull().sum())

Before numerical columns
******************************
Gender                  48
ParentalSupport         22
Online_Classes_Taken    25
dtype: int64
After numerical columns
******************************
Gender                  0
ParentalSupport         0
Online_Classes_Taken    0
dtype: int64

/tmp/ipykernel_990/2678543693.py:8: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  student[col] = student[col].fillna(student[col].mode()[0])

In [50]:
# Check data set after handling missing values
student.isnull().sum()

Gender                       0
AttendanceRate               0
StudyHoursPerWeek            0
PreviousGrade                0
ExtracurricularActivities    0
ParentalSupport              0
FinalGrade                   0
Study_Hours                  0
Attendance_                  0
Online_Classes_Taken         0
dtype: int64

## Step 9 – Remove Duplicate Records

In [51]:
print("Number of duplicate rows:", student.duplicated().sum())

student = student.drop_duplicates()

print("Shape after removing duplicates:", student.shape)

Number of duplicate rows: 0
Shape after removing duplicates: (1000, 10)

The dataset contains 0 duplicate records therefore, no rows were removed.The dataset remains 1000 rows * 10 columns after duplicate checking.

## Step 10 – Encode Categorical Variables

In [52]:
print("Categorical Columns:")
print(cat_cols)

Categorical Columns:
Index(['Gender', 'ParentalSupport', 'Online_Classes_Taken'], dtype='object')

In [54]:
le = LabelEncoder()

for col in cat_cols:
    student[col] = le.fit_transform(student[col])

student.head()

,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade,Study_Hours,Attendance_,Online_Classes_Taken
0,1,85.0,15.0,78.0,1.0,0,80.0,4.8,59.0,0
1,0,90.0,20.0,85.0,2.0,2,87.0,2.2,70.0,1
2,1,78.0,10.0,65.0,0.0,1,68.0,4.6,92.0,0
3,1,92.0,25.0,90.0,3.0,0,92.0,2.9,96.0,0
4,0,88.0,18.0,82.0,2.0,2,85.0,4.1,97.0,1

* Categorical variables are converted into numerical values so that they can be processed by Machine Learning algorithms.

## Step 11 – Separate Features and Target

In [55]:
X = student.drop('FinalGrade', axis=1)  # Feature
y = student['FinalGrade'] # Target

* The dataset is divided into **independent features (X)** and the **target variable (y**) before splitting into training and testing data.

## Step 12 – Split the Dataset into Training and Testing Data

In [56]:
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.2,
                                                    random_state=42
                                                    )

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (800, 9)
X_test : (200, 9)
y_train: (800,)
y_test : (200,)

* The dataset is divided into **80% training data** and **20% testing data**. The training data is used to train the ML model, while the testing data is used to evaluate its performance.

## Step 13 – Feature Scaling

In [57]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

* Feature scaling is performed after train-test splitting. The scaler is fitted only on the training data and then applied to the testing data to prevent data leakage.

## Step 14 – Verify the Preprocessed Data

In [58]:
print("Training data shape:", X_train_scaled.shape)
print("Testing data shape :", X_test_scaled.shape)

Training data shape: (800, 9)
Testing data shape : (200, 9)

In [59]:
print("\nMissing values in X_train:")
print(X_train.isnull().sum().sum())

Missing values in X_train:
0

In [60]:
print("\nMissing values in X_test:")
print(X_test.isnull().sum().sum())

Missing values in X_test:
0

In [61]:
print("\nFirst 5 rows of scaled training data:")
print(X_train_scaled[:5])

First 5 rows of scaled training data:
[[ 0.87299172  0.72376272  0.69798871 -0.05007211  1.47116139  1.24123319
  -1.05416041 -1.40381823 -1.02275892]
 [ 0.87299172 -2.23973074 -1.59183952  0.05133976  1.47116139  0.03761313
   0.78115695 -0.08355854  0.97774752]
 [-1.14548624  0.72376272 -0.4469254  -0.75995518  1.47116139  1.24123319
  -1.2659278  -1.19535618 -1.02275892]
 [ 0.87299172  0.72376272  0.69798871 -1.77407385 -1.43962784  0.03761313
   1.27528086  1.51465056 -1.02275892]
 [ 0.87299172  0.30040651  0.37087039 -0.75995518 -1.43962784 -1.16600694
  -0.0659126  -1.05638147  0.97774752]]

The dataset has been successfully preprocessed.
Missing and invalid values have been handled, categorical variables have been encoded, and numerical features have been standardized without data leakage.

* The Student Performance dataset has been successfully cleaned and transformed. The preprocessed training and testing data are now ready to be used as input for a Machine Learning algorithm.

## Step 15 – Save the Cleaned Dataset

In [62]:
student.to_csv("cleaned_student_performance.csv", index=False)
print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

Step 16 – Load and Verify the Cleaned Dataset

In [ ]:
cleaned_student = pd.read_csv("cleaned_student_performance.csv")

print("Cleaned Dataset Shape:", cleaned_student.shape)
print(cleaned_student.head())


The cleaned dataset is successfully saved and loaded without errors. It is ready for future Machine Learning applications.

After these, our **Experiment 1** is complete.